name: CI/CD Blog Psican치lise

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 游닌 Baixar c칩digo
        uses: actions/checkout@v4

      - name: 游릭 Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 游닍 Instalar depend칡ncias
        run: npm install

      - name: 游빍 Rodar testes
        run: npm test

      - name: 游늭 Copiar arquivos HTML para pasta de build
        run: |
          mkdir public
          cp src/index.html public/index.html

      - name: 游 Deploy no GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public